config/routes.rb
Rails.application.routes.draw do
  get 'religions/index'

  resources :positions

  resources :departments

  resources :languages

  resources :home
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root 'home#index'
  get '/user', to: 'users#index'

     namespace :admin do
	   
		resources :religions
		resources :geocountries
		resources :geodistricts
		resources :geocities
		resources :geostates
     end
end

app/models/department.rb
class Department < ActiveRecord::Base
	self.table_name = 'masters_departments'
	before_create :set_code
	
	def generate_code(size=6)
		charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
		(0...size).map{ charset.to_a[rand(charset.size)] }.join
	end

	def set_code
		self.code = self.generate_code(6);
	end
end

app/models/geocity.rb
class Geocity < ActiveRecord::Base
	self.table_name = 'reference_geo_cities'
	belongs_to :geostates
	has_many :geodistricts
	
	validates :short, :name, presence: true
end

app/models/geocountry.rb
class Geocountry < ActiveRecord::Base
	self.table_name = 'reference_geo_countries'
	has_many :geostates
	
	validates :short, :name, presence: true
end

app/models/geodistrict.rb
class Geodistrict < ActiveRecord::Base
	self.table_name = 'reference_geo_districts'
	belongs_to :geocities
	
	validates :short, :name, presence: true
end

app/models/geostate.rb
class Geostate < ActiveRecord::Base
	self.table_name = 'reference_geo_states'
	belongs_to :geocountries
	has_many :geocities
	
	validates :short, :name, presence: true
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	self.table_name = 'reference_grades'
	
	validates :grade, presence: true
end

app/models/language.rb
class Language < ActiveRecord::Base
	self.table_name = 'reference_languages'
end

app/models/level.rb
class Section < ActiveRecord::Base
	self.table_name = 'masters_sections'
	
	validates :name, presence: true
end

app/models/position.rb
class Position < ActiveRecord::Base
	self.table_name = 'masters_positions'
end

app/models/religion.rb
class Religion < ActiveRecord::Base
	self.table_name = 'reference_religions'
	
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/religions_controller.rb
class Admin::ReligionsController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!

  respond_to :html

  def index
    @religions = Religion.all
    respond_with(@religions)
  end

  def show
    respond_with(@religion)
  end

  def new
    @religion = Religion.new
    respond_with(@religion)
  end

  def edit
  end

  def create
    @religion = Religion.new(religion_params)
    @religion.save
    respond_with(@religion)
  end

  def update
    @religion.update(religion_params)
    respond_with(@religion)
  end

  def destroy
    @religion.destroy
    respond_with(@religion)
  end

  private
    def set_religion
      @religion = Religion.find(params[:id])
    end

    def religion_params
      #params[:religion]
	  params.require(:religion).permit(:name)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
	def role
		if current_user.role = 0
			@role = "User"
		elsif current_user.role = 1
			@role = "Admin"
		else
			@role = "Undefined"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/geocities_helper.rb
module GeocitiesHelper
end

app/helpers/geostates_helper.rb
module GeostatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/raligions_helper.rb
module RaligionsHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/religions/_form.html.erb
<%= form_for([:admin,@religion]) do |f| %>
  <% if @religion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@religion.errors.count, "error") %> prohibited this religion from being saved:</h2>

      <ul>
      <% @religion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/religions/edit.html.erb
<h1>Editing religion</h1>

<%= render 'form' %>

<%= link_to 'Show', @religion %> |
<%= link_to 'Back', religions_path %>

app/views/admin/religions/index.html.erb
<!-- PAGE TITLE -->
<div class="page-title">                    
	<h2><span class="fa"></span> Listing Religion</h2>
</div>
<!-- END PAGE TITLE -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
	<div class="row">
		<div class="col-md-12">
			
			<!-- START DEFAULT DATATABLE -->
			<div class="panel panel-default">
				<div class="panel-heading">                                
					<h3 class="panel-title">Default</h3>
					<ul class="panel-controls">
						<li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
						<li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
						<li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
					</ul>                                
				</div>
				<div class="panel-body">

<table class="table table-striped">
  <thead>
    <tr>
	  <th>ID</th>
	  <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @religions.each do |religion| %>
      <tr>
		<td><%= religion.id %></td>
		<td><%= religion.name %></td>
        <!--
        <td><%= link_to 'Show', admin_religion_path( religion ) %></td>
        <td><%= link_to 'Edit', edit_admin_religion_path( religion ) %></td>
        <td><%= link_to 'Destroy', admin_religion_path( religion ), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Religion', new_admin_religion_path %>

				</div>
			</div>
			<!-- END DEFAULT DATATABLE -->
			
		</div>
	</div>
</div>
<!-- END PAGE CONTENT WRAPPER -->

app/views/admin/religions/new.html.erb
<h1>New religion</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_religions_path %>

app/views/admin/religions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @religion.name %>
</p>

<%= link_to 'Edit', edit_religion_path(@religion) %> |
<%= link_to 'Back', religions_path %>

app/views/religions/index.html.erb
<h1>Religions#index</h1>
<p>Find me in app/views/religions/index.html.erb</p>