config/routes.rb
Rails.application.routes.draw do
  get 'religions/index'

  resources :positions

  resources :departments

  resources :languages

  resources :home
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root 'home#index'
  get '/user', to: 'users#index'

     namespace :admin do
	   
		resources :religions
		resources :geocountries
		resources :geodistricts
		resources :geocities
		resources :geostates
     end
end

app/models/department.rb
class Department < ActiveRecord::Base
	self.table_name = 'masters_departments'
	before_create :set_code
	
	def generate_code(size=6)
		charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
		(0...size).map{ charset.to_a[rand(charset.size)] }.join
	end

	def set_code
		self.code = self.generate_code(6);
	end
end

app/models/geocity.rb
class Geocity < ActiveRecord::Base
	self.table_name = 'reference_geo_cities'
	belongs_to :geostates
	has_many :geodistricts
	
	validates :short, :name, presence: true
end

app/models/geocountry.rb
class Geocountry < ActiveRecord::Base
	self.table_name = 'reference_geo_countries'
	has_many :geostates
	
	validates :short, :name, presence: true
end

app/models/geodistrict.rb
class Geodistrict < ActiveRecord::Base
	self.table_name = 'reference_geo_districts'
	belongs_to :geocities
	
	validates :short, :name, presence: true
end

app/models/geostate.rb
class Geostate < ActiveRecord::Base
	self.table_name = 'reference_geo_states'
	belongs_to :geocountries
	has_many :geocities
	
	validates :short, :name, presence: true
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	self.table_name = 'reference_grades'
	
	validates :grade, presence: true
end

app/models/language.rb
class Language < ActiveRecord::Base
	self.table_name = 'reference_languages'
end

app/models/level.rb
class Section < ActiveRecord::Base
	self.table_name = 'masters_sections'
	
	validates :name, presence: true
end

app/models/position.rb
class Position < ActiveRecord::Base
	self.table_name = 'masters_positions'
end

app/models/religion.rb
class Religion < ActiveRecord::Base
	self.table_name = 'reference_religions'
	
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/geocities_controller.rb
class Admin::GeocitiesController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
  #before_action :set_geocity, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @geocities = Geocity.all
    respond_with(@geocities)
  end

  def show
    respond_with(@geocity)
  end

  def new
    @geocity = Geocity.new
    respond_with(@geocity)
  end

  def edit
  end

  def create
    @geocity = Geocity.new(geocity_params)
    @geocity.save
    respond_with(@geocity)
  end

  def update
    @geocity.update(geocity_params)
    respond_with(@geocity)
  end

  def destroy
    @geocity.destroy
    respond_with(@geocity)
  end

  private
    def set_geocity
      @geocity = Geocity.find(params[:id])
    end

    def geocity_params
      params.require(:geocity).permit(:short, :name)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
	def role
		if current_user.role = 0
			@role = "User"
		elsif current_user.role = 1
			@role = "Admin"
		else
			@role = "Undefined"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/geocities_helper.rb
module GeocitiesHelper
end

app/helpers/geostates_helper.rb
module GeostatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/raligions_helper.rb
module RaligionsHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/geocities/_form.html.erb
<%= form_for(@geocity) do |f| %>
  <% if @geocity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@geocity.errors.count, "error") %> prohibited this geocity from being saved:</h2>

      <ul>
      <% @geocity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label :short %><br/>
	<%= f.text_field :short %>
  </div>
  
  <div class="field">
	<%= f.label :name %><br/>
	<%= f.text_field :name %>
  </div>
  
  <div class="field">
	<%= f.label :sort_order %><br/>
	<%= f.text_field :sort_order %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/geocities/edit.html.erb
<h1>Editing geocity</h1>

<%= render 'form' %>

<%= link_to 'Show', @geocity %> |
<%= link_to 'Back', geocities_path %>

app/views/admin/geocities/index.html.erb
<h1>Listing geocities</h1>

<table class="table table-striped">
  <thead>
    <tr>
	  <th>ID</th>
	  <th>Short</th>
	  <th>Name</th>
	  <th>Sort Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geocities.each do |geocity| %>
      <tr>
	    <td><%= geocity.id %></td>
		<td><%= geocity.short %></td>
		<td><%= geocity.name %></td>
		<td><%= geocity.sort_order %></td>
        <td><%= link_to 'Show', geocity %></td>
        <td><%= link_to 'Edit', edit_geocity_path(geocity) %></td>
        <td><%= link_to 'Destroy', geocity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geocity', new_geocity_path %>

app/views/admin/geocities/new.html.erb
<h1>New geocity</h1>

<%= render 'form' %>

<%= link_to 'Back', geocities_path %>

app/views/admin/geocities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short:</strong>
  <%= @geocity.short %>
</p>

<p>
  <strong>Name:</strong>
  <%= @geocity.name %>
</p>

<p>
  <strong>Sort Order:</strong>
  <%= @geocity.sort_order %>
</p>

<%= link_to 'Edit', edit_geocity_path(@geocity) %> |
<%= link_to 'Back', geocities_path %>