config/routes.rb
Rails.application.routes.draw do
  get 'religions/index'

  resources :positions

  resources :departments

  resources :languages

  resources :home
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root 'home#index'
  get '/user', to: 'users#index'

     namespace :admin do
	   
		resources :religions
		resources :geocountries
		resources :geodistricts
		resources :geocities
		resources :geostates
     end
end

app/models/department.rb
class Department < ActiveRecord::Base
	self.table_name = 'masters_departments'
	before_create :set_code
	
	def generate_code(size=6)
		charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
		(0...size).map{ charset.to_a[rand(charset.size)] }.join
	end

	def set_code
		self.code = self.generate_code(6);
	end
end

app/models/geocity.rb
class Geocity < ActiveRecord::Base
	self.table_name = 'reference_geo_cities'
	belongs_to :geostates
	has_many :geodistricts
	
	validates :short, :name, presence: true
end

app/models/geocountry.rb
class Geocountry < ActiveRecord::Base
	self.table_name = 'reference_geo_countries'
	has_many :geostates
	
	validates :short, :name, presence: true
end

app/models/geodistrict.rb
class Geodistrict < ActiveRecord::Base
	self.table_name = 'reference_geo_districts'
	belongs_to :geocities
	
	validates :short, :name, presence: true
end

app/models/geostate.rb
class Geostate < ActiveRecord::Base
	self.table_name = 'reference_geo_states'
	belongs_to :geocountries
	has_many :geocities
	
	validates :short, :name, presence: true
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	self.table_name = 'reference_grades'
	
	validates :grade, presence: true
end

app/models/language.rb
class Language < ActiveRecord::Base
	self.table_name = 'reference_languages'
end

app/models/level.rb
class Section < ActiveRecord::Base
	self.table_name = 'masters_sections'
	
	validates :name, presence: true
end

app/models/position.rb
class Position < ActiveRecord::Base
	self.table_name = 'masters_positions'
end

app/models/religion.rb
class Religion < ActiveRecord::Base
	self.table_name = 'reference_religions'
	
	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/geocountries_controller.rb
class Admin::GeocountriesController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
  #before_action :set_geocountry, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @geocountries = Geocountry.all
    respond_with(@geocountries)
  end

  def show
    respond_with(@geocountry)
  end

  def new
    @geocountry = Geocountry.new
    respond_with(@geocountry)
  end

  def edit
  end

  def create
    @geocountry = Geocountry.new(geocountry_params)
    @geocountry.save
    respond_with(@geocountry)
  end

  def update
    @geocountry.update(geocountry_params)
    respond_with(@geocountry)
  end

  def destroy
    @geocountry.destroy
    respond_with(@geocountry)
  end

  private
    def set_geocountry
      @geocountry = Geocountry.find(params[:id])
    end

    def geocountry_params
	  params.require(:geocountry).permit(:short, :name)
    end
end

app/controllers/geocountries_controller.rb
class Admin::GeocountriesController < ApplicationController
  def index
    @geocountries = Geocountry.all
  end
end

app/helpers/admin_helper.rb
module AdminHelper
	def role
		if current_user.role = 0
			@role = "User"
		elsif current_user.role = 1
			@role = "Admin"
		else
			@role = "Undefined"
		end
	end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/geocities_helper.rb
module GeocitiesHelper
end

app/helpers/geocountries_helper.rb
module GeocountriesHelper
end

app/helpers/geostates_helper.rb
module GeostatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/raligions_helper.rb
module RaligionsHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/geocountries/_form.html.erb
<%= form_for([:admin,@geocountry], html: {class: "form-horizontal"}) do |f| %>
  <% if @geocountry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@geocountry.errors.count, "error") %> prohibited this geocountry from being saved:</h2>

      <ul>
      <% @geocountry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">                                        
	<label class="col-md-3 col-xs-12 control-label"><%= f.label :short %></label>
	<div class="col-md-6 col-xs-12">
		<div class="input-group">
			<span class="input-group-addon"><span class="fa fa-pencil"></span></span>
			<%= f.text_field :short, class:"form-control" %>
		</div>            
		<span class="help-block"></span>
	</div>
</div>

<div class="form-group">                                        
	<label class="col-md-3 col-xs-12 control-label"><%= f.label :name %></label>
	<div class="col-md-6 col-xs-12">
		<div class="input-group">
			<span class="input-group-addon"><span class="fa fa-pencil"></span></span>
			<%= f.text_field :name, class:"form-control" %>
		</div>            
		<span class="help-block"></span>
	</div>
</div>

<div class="form-group">                                        
	<label class="col-md-3 col-xs-12 control-label"><%= f.label :sort_order %></label>
	<div class="col-md-6 col-xs-12">
		<div class="input-group">
			<span class="input-group-addon"><span class="fa fa-pencil"></span></span>
			<%= f.text_field :sort_order, class:"form-control" %>
		</div>            
		<span class="help-block"></span>
	</div>
</div>
  
<div class="panel-footer">
	<%= f.submit 'Clear Form', :type => 'reset', class: 'btn btn-default' %>
	<%= f.submit 'Submit', :type => 'submit', class: 'btn btn-primary pull-right' %>
</div>
  
<% end %>

app/views/admin/geocountries/edit.html.erb
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
	<div class="row">
		<div class="col-md-12">
		
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><strong>Editing</strong> Country</h3>
					<ul class="panel-controls">
						<li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
					</ul>
				</div>
				
<%= render 'form' %>

<%= link_to 'Show', @geocountry %> |
<%= link_to 'Back', geocountries_path %>
				
			</div>
			
		</div>
	</div>
</div>
<!-- END PAGE CONTENT WRAPPER -->

app/views/admin/geocountries/index.html.erb
<!-- PAGE TITLE -->
<div class="page-title">                    
	<h2><span class="fa"></span> Listing Country</h2>
</div>
<!-- END PAGE TITLE -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
	<div class="row">
		<div class="col-md-12">
			
			<!-- START DEFAULT DATATABLE -->
			<div class="panel panel-default">
				<div class="panel-heading">                                
					<h3 class="panel-title">Default</h3>
					<ul class="panel-controls">
						<li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
						<li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
						<li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
					</ul>                                
				</div>
				<div class="panel-body">
			
<table class="table datatable">
  <thead>
    <tr>
	  <th>ID</th>
	  <th>Short</th>
	  <th>Name</th>
	  <th>Sort Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geocountries.each do |geocountry| %>
      <tr>
	    <td><%= geocountry.id %></td>
		<td><%= geocountry.short %></td>
		<td><%= geocountry.name %></td>
		<td><%= geocountry.sort_order %></td>
        <!--
		<td><%= link_to 'Show', admin_geocountry_path( geocountry ) %></td>
        <td><%= link_to 'Edit', edit_admin_geocountry_path( geocountry ) %></td>
        <td><%= link_to 'Destroy', admin_geocountry_path( geocountry ), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geocountry', new_admin_geocountry_path %>

				</div>
			</div>
			<!-- END DEFAULT DATATABLE -->
			
		</div>
	</div>
</div>
<!-- END PAGE CONTENT WRAPPER -->

app/views/admin/geocountries/new.html.erb
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
	<div class="row">
		<div class="col-md-12">
		
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><strong>New</strong> Country</h3>
					<ul class="panel-controls">
						<li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
					</ul>
				</div>
				
<%= render 'form' %>

<%= link_to 'Back', admin_geocountries_path %>

			</div>
			
		</div>
	</div>
</div>
<!-- END PAGE CONTENT WRAPPER -->

app/views/admin/geocountries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Short:</strong>
  <%= @geocountry.short %>
</p>

<p>
  <strong>Name:</strong>
  <%= @geocountry.name %>
</p>

<p>
  <strong>Sort Order:</strong>
  <%= @geocountry.sort_order %>
</p>

<%= link_to 'Edit', edit_admin_geocountry_path(@geocountry) %> |
<%= link_to 'Back', geocountries_path %>